services:
  - type: web
    name: django-app
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: gunicorn qrproject.wsgi
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
    aptPackages:
      - libzbar0
